config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'

  resources :recipes, only: %i[index show]
end

app/models/chef.rb
# frozen_string_literal: true

class Chef
  attr_reader :id, :name, :raw

  def initialize(raw)
    @id = raw.id
    @name = raw.fields[:name]
    @raw = raw
  end
end

app/models/entry.rb
# frozen_string_literal: true

class Entry
  def entries(content_type:)
    MarleySpoonApi.client.entries(content_type: content_type)
  end
end

app/models/marley_spoon_api.rb
# frozen_string_literal: true

class MarleySpoonApi
  def self.client
    @client ||= contentful_client
  end

  def self.contentful_client
    Contentful::Client.new(
      space: ENV['SPACE_ID'],
      environment: ENV['ENVIRONMENT'],
      access_token: ENV['ACCESS_TOKEN']
    )
  end
end

app/models/photo.rb
# frozen_string_literal: true

class Photo
  attr_reader :id, :url, :raw

  def initialize(raw)
    @id = raw.id
    @raw = raw
    @url = raw.url
  end
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe
  attr_reader :id, :title, :calories, :description, :chef, :photo, :tags

  def initialize(id, fields)
    create(id, fields)
  end

  def formatted_description
    Kramdown::Document.new(description).to_html.html_safe
  end

  def self.all(page: '0')
    recipes = items(page)
    return [] if recipes.empty?

    recipes.map { |item| new(item.id, item.fields) }
  end

  def self.items(page)
    cache[page] ||= entries(content_type: 'recipe').items
  end

  def self.entries(content_type:)
    MarleySpoonApi.client.entries(content_type: content_type)
  end

  def self.find_by_id(id)
    all if cache.empty?
    cache[id]
  end

  def self.cache
    @cache ||= {}
  end

  private

  def create(id, fields)
    @id = id
    @title =  fields[:title]
    @calories = fields[:calories]
    @description = fields[:description]

    associate_records_for(fields)

    Recipe.cache[id] = self

    self
  end

  def associate_records_for(fields)
    @chef = Chef.new(fields[:chef]) if fields[:chef]
    @photo = Photo.new(fields[:photo]) if fields[:photo]

    @tags = if fields[:tags].present?
              fields[:tags].map { |tag| Tag.new(tag) }
            else
              []
            end
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag
  attr_reader :id, :name, :raw

  def initialize(raw)
    @id = raw.id
    @name = raw.fields[:name]
    @raw = raw
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by_id(params[:id])
    error_404 if @recipe.nil?
  end

  private

  def error_404
    render file: 'public/404.html', status: :not_found
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_navbar.html.slim
nav.navbar.justify-content-between.background-red.mb-4
  .container
    a.navbar-brand.navbar-logo.text-dark href="/"
    = link_to('View Menu', recipes_path, class: 'navbar-link active recipe-link')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MarleySpoon
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.background-light-grey
    = render "layouts/navbar"
    .container
      = yield

app/views/recipes/index.slim
.row
  - if @recipes.present?
    - @recipes.each do |recipe|
      .col-6
        = link_to(recipe_path(recipe.id), class: 'recipe-link') do
          .card.mb-2
            img.card-img-top alt=(recipe.id) src=recipe.photo.url
            .card-body
              - title = recipe.title.split('with')[0].strip
              - subtitle = recipe.title.split('with')[1]&.strip
              h5.card-title = title
              - if subtitle
                .card-subtitle with #{subtitle}

app/views/recipes/show.slim
.container
  .row
    .col-2
    .col-8
      .recipe-hero
        img.recipe-hero-image alt=(@recipe.id) src=@recipe.photo.url
        h4.mt-3.mb-4 = @recipe.title
        - if @recipe.tags.present?
          .recipe-tags.mb-4
            ul.recipe-tags
              - @recipe.tags.each do |tag|
                li.recipe-tags-attributes.mr-2 = tag.name
        .description.mb-3
          .topic.mb-3
            b What's cooking
          .details = @recipe.formatted_description
        - if @recipe.chef
          .chef Shared with you by: <b>#{@recipe.chef.name}<b>